<?php require_once __DIR__ . '/../includes/config.php'; require_once __DIR__ . '/../includes/auth.php'; require_login();
$type=$_GET['type']??'student'; $from=$_GET['from']??date('Y-m-d'); $to=$_GET['to']??date('Y-m-d'); $format=$_GET['format']??'csv'; $route=$_GET['route']??'both';
$busId=(int)($_GET['bus_id']??0); $classId=(int)($_GET['class_id']??0); $studentIds=array_map('intval',$_GET['student_ids']??[]);
$params=[$from,$to]; $where='a.attendance_date BETWEEN ? AND ?'; if($route!=='both'){ $where.=' AND a.route=?'; $params[]=$route; }
if($type==='bus' && $busId>0){$where.=' AND s.bus_id=?';$params[]=$busId;} if($type==='class' && $classId>0){$where.=' AND s.class_id=?';$params[]=$classId;} if($type==='student' && $studentIds){$where.=' AND s.id IN ('.implode(',',array_fill(0,count($studentIds),'?')).')';$params=array_merge($params,$studentIds);} 
$base=' FROM attendance a JOIN students s ON s.id=a.student_id LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN buses b ON b.id=s.bus_id WHERE '.$where;
if($type==='bus') $sql='SELECT a.attendance_date,s.code,COUNT(*) number_of_students,SUM(a.status="attending") attended,SUM(a.status="absent") absent,SUM(a.status="attending without bus") without_bus,COALESCE(b.name,"No bus") bus,a.route'.$base.' GROUP BY a.attendance_date,s.code,bus,a.route ORDER BY a.attendance_date';
elseif($type==='class') $sql='SELECT a.attendance_date,c.name class,GROUP_CONCAT(DISTINCT COALESCE(b.name,"No bus") SEPARATOR ", ") buses,COUNT(*) number_of_students,SUM(a.status="absent") absent,SUM(a.status="attending") attended,SUM(a.status="attending without bus") without_bus'.$base.' GROUP BY a.attendance_date,c.name ORDER BY a.attendance_date,c.name';
else $sql='SELECT s.code,s.name,c.name class,COALESCE(b.name,"No bus") bus,a.attendance_date,a.route,a.status'.$base.' ORDER BY s.name,a.attendance_date';
$st=$pdo->prepare($sql);$st->execute($params);$rows=$st->fetchAll();
if($type==='student' && $rows){ $dates=[]; foreach($rows as $r)$dates[$r['attendance_date']]=1; $dates=array_keys($dates); sort($dates); $by=[]; foreach($rows as $r){$k=$r['code'].'|'.$r['name'].'|'.$r['class'].'|'.$r['bus'].'|'.$r['route']; $by[$k]=$by[$k]??['code'=>$r['code'],'student_name'=>$r['name'],'class'=>$r['class'],'bus'=>$r['bus'],'route'=>$r['route']]; $by[$k][$r['attendance_date']]=$r['status'];} $out=[]; foreach($by as $v){ foreach($dates as $d){ if(!isset($v[$d])) $v[$d]=''; } $out[]=$v; } $rows=$out; }
if($format==='csv'){ header('Content-Type:text/csv; charset=UTF-8'); header('Content-Disposition: attachment; filename="report.csv"'); echo "\xEF\xBB\xBF"; $o=fopen('php://output','w'); if($rows) fputcsv($o,array_keys($rows[0])); foreach($rows as $r) fputcsv($o,$r); fclose($o); exit; }
header('Content-Type:text/html; charset=UTF-8'); echo '<!doctype html><html><meta charset="utf-8"><style>table{width:100%;border-collapse:collapse}th,td{border:1px solid #444;padding:6px}</style><table>'; if($rows){echo '<tr>';foreach(array_keys($rows[0]) as $h)echo '<th>'.h($h).'</th>';echo '</tr>'; foreach($rows as $r){echo '<tr>';foreach($r as $v)echo '<td>'.h((string)$v).'</td>';echo '</tr>';}} echo '</table><script>window.print()</script></html>';
