<?php require_once __DIR__ . '/../includes/config.php'; require_once __DIR__ . '/../includes/auth.php'; require_once __DIR__ . '/../includes/layout.php'; require_login();
$type=$_GET['type']??'student'; $from=$_GET['from']??date('Y-m-d'); $to=$_GET['to']??date('Y-m-d');
$busId=(int)($_GET['bus_id']??0); $classId=(int)($_GET['class_id']??0); $studentId=(int)($_GET['student_id']??0);
$routes=array_map('trim',explode(',',(string)$pdo->query("SELECT setting_value FROM settings WHERE setting_key='routes'")->fetchColumn()));
$route=$_GET['route']??'both';
$buses=$pdo->query('SELECT id,name FROM buses ORDER BY name')->fetchAll(); $classes=$pdo->query('SELECT id,name FROM classes ORDER BY name')->fetchAll(); $students=$pdo->query('SELECT id,name,code FROM students ORDER BY name')->fetchAll();
$params=[$from,$to]; $where='a.attendance_date BETWEEN ? AND ?'; if($route!=='both'){ $where.=' AND a.route=?'; $params[]=$route; }
if($type==='bus' && $busId>0){$where.=' AND s.bus_id=?';$params[]=$busId;} if($type==='class' && $classId>0){$where.=' AND s.class_id=?';$params[]=$classId;} if($type==='student' && $studentId>0){$where.=' AND s.id=?';$params[]=$studentId;}
$sql="SELECT a.attendance_date,s.code,s.name,c.name class,COALESCE(b.name,'No bus') bus,a.route,a.status FROM attendance a JOIN students s ON s.id=a.student_id LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN buses b ON b.id=s.bus_id WHERE $where ORDER BY a.attendance_date,b.name,c.name,s.name";
$st=$pdo->prepare($sql);$st->execute($params);$rows=$st->fetchAll();
ui_start('Reports');?>
<div class="card"><h2>Reports</h2><form method="get" class="grid"><select name="type" onchange="this.form.submit()"><option value="student" <?=$type==='student'?'selected':''?>>Student</option><option value="bus" <?=$type==='bus'?'selected':''?>>Bus</option><option value="class" <?=$type==='class'?'selected':''?>>Class</option></select><input type="date" name="from" value="<?=h($from)?>"><input type="date" name="to" value="<?=h($to)?>"><select name="route"><option value="both" <?=$route==='both'?'selected':''?>>Both routes</option><?php foreach($routes as $r):?><option <?=$route===$r?'selected':''?>><?=h($r)?></option><?php endforeach;?></select><?php if($type==='bus'):?><select name="bus_id"><option value="0">All buses</option><?php foreach($buses as $b):?><option value="<?=$b['id']?>" <?=$busId===$b['id']?'selected':''?>><?=h($b['name'])?></option><?php endforeach;?></select><?php endif; ?><?php if($type==='class'):?><select name="class_id"><option value="0">All classes</option><?php foreach($classes as $c):?><option value="<?=$c['id']?>" <?=$classId===$c['id']?'selected':''?>><?=h($c['name'])?></option><?php endforeach;?></select><?php endif; ?><?php if($type==='student'):?><select name="student_id"><option value="0">All students</option><?php foreach($students as $s):?><option value="<?=$s['id']?>" <?=$studentId===$s['id']?'selected':''?>><?=h($s['code'].' - '.$s['name'])?></option><?php endforeach;?></select><?php endif; ?><button class="btn">View Online</button></form><div class="actions"><a class="btn" href="/reports/export.php?<?=http_build_query($_GET + ['from'=>$from,'to'=>$to,'route'=>$route,'type'=>$type,'bus_id'=>$busId,'class_id'=>$classId,'student_id'=>$studentId,'format'=>'pdf'])?>">Print / PDF</a><a class="btn" href="/reports/export.php?<?=http_build_query($_GET + ['from'=>$from,'to'=>$to,'route'=>$route,'type'=>$type,'bus_id'=>$busId,'class_id'=>$classId,'student_id'=>$studentId,'format'=>'csv'])?>">Download CSV</a></div></div>
<div class="card"><table><?php if($rows):?><tr><?php foreach(array_keys($rows[0]) as $h):?><th><?=h($h)?></th><?php endforeach;?></tr><?php foreach($rows as $r):?><tr><?php foreach($r as $v):?><td><?=h((string)$v)?></td><?php endforeach;?></tr><?php endforeach; else:?><tr><td>No rows</td></tr><?php endif;?></table></div>
<?php ui_end(); ?>
