<?php require_once __DIR__ . '/../includes/config.php'; require_once __DIR__ . '/../includes/auth.php'; require_once __DIR__ . '/../includes/layout.php'; require_login();
$date=$_POST['attendance_date']??($_GET['attendance_date']??date('Y-m-d'));
$routes=array_map('trim',explode(',',(string)$pdo->query("SELECT setting_value FROM settings WHERE setting_key='routes'")->fetchColumn()));
$statuses=array_map('trim',explode(',',(string)$pdo->query("SELECT setting_value FROM settings WHERE setting_key='attendance_statuses'")->fetchColumn()));
$route=$_POST['route']??($_GET['route']??($routes[0]??'arriving')); $busFilter=(int)($_POST['bus_id']??($_GET['bus_id']??0)); $qText=trim($_POST['q']??($_GET['q']??''));
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['status'])){ foreach($_POST['status'] as $id=>$st){ $pdo->prepare('REPLACE INTO attendance (attendance_date,student_id,route,status) VALUES (?,?,?,?)')->execute([$date,(int)$id,$route,$st]); }}
$buses=$pdo->query('SELECT id,name FROM buses ORDER BY name')->fetchAll();
$params=[]; $where=[]; if($busFilter>0){$where[]='s.bus_id=?';$params[]=$busFilter;} if($qText!==''){ $where[]='(s.code LIKE ? OR s.name LIKE ?)'; $params[]="%$qText%"; $params[]="%$qText%"; }
$sql='SELECT s.id,s.code,s.name,c.name class_name,b.name bus_name FROM students s LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN buses b ON b.id=s.bus_id'; if($where)$sql.=' WHERE '.implode(' AND ',$where); $sql.=' ORDER BY c.name,s.name';
$st=$pdo->prepare($sql);$st->execute($params);$students=$st->fetchAll();
$ex=[];$s=$pdo->prepare('SELECT student_id,status FROM attendance WHERE attendance_date=? AND route=?');$s->execute([$date,$route]);foreach($s->fetchAll() as $r)$ex[$r['student_id']]=$r['status']; ui_start('Attendance');?>
<div class="card"><h2>Attendance</h2><form method="get"><div class="grid"><input type="date" name="attendance_date" value="<?=h($date)?>"><select name="route"><?php foreach($routes as $r):?><option <?=$route===$r?'selected':''?>><?=h($r)?></option><?php endforeach;?></select><select name="bus_id"><option value="0">All buses</option><?php foreach($buses as $b):?><option value="<?=$b['id']?>" <?=$busFilter===$b['id']?'selected':''?>><?=h($b['name'])?></option><?php endforeach;?></select><input name="q" value="<?=h($qText)?>" placeholder="Search code or name"><button class="btn">Filter</button></div></form><form method="post"><input type="hidden" name="attendance_date" value="<?=h($date)?>"><input type="hidden" name="route" value="<?=h($route)?>"><input type="hidden" name="bus_id" value="<?=$busFilter?>"><input type="hidden" name="q" value="<?=h($qText)?>"><table><tr><th>Code</th><th>Name</th><th>Class</th><th>Bus</th><th>Status</th></tr><?php foreach($students as $s):$cur=$ex[$s['id']]??($statuses[0]??'attending');?><tr><td><?=h($s['code'])?></td><td><?=h($s['name'])?></td><td><?=h($s['class_name'])?></td><td><?=h($s['bus_name']??'No bus')?></td><td><select name="status[<?=$s['id']?>]"><?php foreach($statuses as $o):?><option <?=$o===$cur?'selected':''?>><?=h($o)?></option><?php endforeach;?></select></td></tr><?php endforeach;?></table><button class="btn">Save Attendance</button></form></div><?php ui_end(); ?>
