<?php require_once __DIR__ . '/../includes/config.php'; require_once __DIR__ . '/../includes/auth.php'; require_once __DIR__ . '/../includes/layout.php'; require_login();
$date=$_POST['attendance_date']??date('Y-m-d');
$routes=array_map('trim',explode(',',(string)$pdo->query("SELECT setting_value FROM settings WHERE setting_key='routes'")->fetchColumn()));
$statuses=array_map('trim',explode(',',(string)$pdo->query("SELECT setting_value FROM settings WHERE setting_key='attendance_statuses'")->fetchColumn()));
$route=$_POST['route']??($_GET['route']??($routes[0]??'arriving'));
if($_SERVER['REQUEST_METHOD']==='POST'){ foreach($_POST['status']??[] as $id=>$st){ $pdo->prepare('REPLACE INTO attendance (attendance_date,student_id,route,status) VALUES (?,?,?,?)')->execute([$date,(int)$id,$route,$st]); }}
$students=$pdo->query('SELECT s.id,s.code,s.name,c.name class_name,b.name bus_name FROM students s LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN buses b ON b.id=s.bus_id ORDER BY c.name,s.name')->fetchAll();
$ex=[];$q=$pdo->prepare('SELECT student_id,status FROM attendance WHERE attendance_date=? AND route=?');$q->execute([$date,$route]);foreach($q->fetchAll() as $r)$ex[$r['student_id']]=$r['status']; ui_start('Attendance');?>
<div class="card"><h2>Attendance</h2><form method="post"><div class="grid"><input type="date" name="attendance_date" value="<?=h($date)?>"><select name="route"><?php foreach($routes as $r):?><option <?=$route===$r?'selected':''?>><?=h($r)?></option><?php endforeach;?></select><button class="btn">Load / Save</button></div><table><tr><th>Code</th><th>Name</th><th>Class</th><th>Bus</th><th>Status</th></tr><?php foreach($students as $s):$cur=$ex[$s['id']]??($statuses[0]??'attending');?><tr><td><?=h($s['code'])?></td><td><?=h($s['name'])?></td><td><?=h($s['class_name'])?></td><td><?=h($s['bus_name']??'No bus')?></td><td><select name="status[<?=$s['id']?>]"><?php foreach($statuses as $o):?><option <?=$o===$cur?'selected':''?>><?=h($o)?></option><?php endforeach;?></select></td></tr><?php endforeach;?></table><button class="btn">Save Attendance</button></form></div><?php ui_end(); ?>
