<?php require_once __DIR__ . '/../includes/config.php'; require_once __DIR__ . '/../includes/auth.php'; require_once __DIR__ . '/../includes/layout.php'; require_login();
$types=array_map('trim',explode(',',(string)$pdo->query("SELECT setting_value FROM settings WHERE setting_key='complaint_types'")->fetchColumn()));
$statuses=array_map('trim',explode(',',(string)$pdo->query("SELECT setting_value FROM settings WHERE setting_key='complaint_statuses'")->fetchColumn()));
$routes=array_map('trim',explode(',',(string)$pdo->query("SELECT setting_value FROM settings WHERE setting_key='routes'")->fetchColumn()));
$buses=$pdo->query('SELECT id,name FROM buses ORDER BY name')->fetchAll();
$students=$pdo->query('SELECT s.id,s.code,s.name,c.name class_name FROM students s LEFT JOIN classes c ON c.id=s.class_id ORDER BY s.name')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  $studentIds=array_map('intval',$_POST['student_ids']??[]); $studentId=$studentIds? $studentIds[0] : null;
  $adminName = $studentId ? null : ($_SESSION['admin_username'] ?? 'administrator');
  $className=''; if($studentId){ foreach($students as $st){ if((int)$st['id']===$studentId){ $className=$st['class_name']; break; } }}
  $vals=[$_POST['complaint_date'],trim($_POST['complainer_name']),$studentId,$adminName,trim($_POST['relationship_text']),trim($_POST['complaint_text']),$_POST['complaint_main_type'],$_POST['complaint_type'],(int)$_POST['bus_id'],$_POST['route'],$className,trim($_POST['driver_name']),trim($_POST['matron_name']),$_POST['status'],trim($_POST['procedure_note']),trim($_POST['communication_type']),trim($_POST['responsible_name']),(int)($_POST['students_involved_count']?:0)];
  if(!empty($_POST['edit_id'])){ $vals[]=(int)$_POST['edit_id']; $pdo->prepare('UPDATE bus_complaints SET complaint_date=?,complainer_name=?,student_id=?,administrator_name=?,relationship_text=?,complaint_text=?,complaint_main_type=?,complaint_type=?,bus_id=?,route=?,class_name=?,driver_name=?,matron_name=?,status=?,procedure_note=?,communication_type=?,responsible_name=?,students_involved_count=? WHERE id=?')->execute($vals);} else {
    $pdo->prepare('INSERT INTO bus_complaints (complaint_date,complainer_name,student_id,administrator_name,relationship_text,complaint_text,complaint_main_type,complaint_type,bus_id,route,class_name,driver_name,matron_name,status,procedure_note,communication_type,responsible_name,students_involved_count) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute($vals);
  }
}
$edit=null; if(isset($_GET['edit'])){$q=$pdo->prepare('SELECT * FROM bus_complaints WHERE id=?');$q->execute([(int)$_GET['edit']]);$edit=$q->fetch();}
$rows=$pdo->query('SELECT bc.*,b.name bus_name,s.name student_name FROM bus_complaints bc JOIN buses b ON b.id=bc.bus_id LEFT JOIN students s ON s.id=bc.student_id ORDER BY bc.id DESC')->fetchAll();
ui_start('Complain System');?>
<div class="card"><h2>Bus Complain</h2><form method="post" class="grid"><input type="hidden" name="edit_id" value="<?= (int)($edit['id']??0) ?>"><div><label>Who is the complainer</label><input name="complainer_name" value="<?=h($edit['complainer_name']??'')?>" required></div><div><label>Date</label><input type="date" name="complaint_date" value="<?=h($edit['complaint_date']??date('Y-m-d'))?>"></div><div><label>Student (searchable multi-select)</label><div id="student-ms"></div></div><div><label>Status</label><select name="status"><?php foreach($statuses as $s):?><option <?=($edit['status']??'')===$s?'selected':''?>><?=h($s)?></option><?php endforeach;?></select></div><div><label>Procedure</label><textarea name="procedure_note" class="bigtext" required><?=h($edit['procedure_note']??'')?></textarea></div><div><label>The complain / incident</label><textarea name="complaint_text" class="bigtext" required><?=h($edit['complaint_text']??'')?></textarea></div><button class="btn">Save Complain</button></form></div>
<div class="card"><table><tr><th>ID</th><th>Date</th><th>Complainer</th><th>Student</th><th>Status</th><th>Action</th></tr><?php foreach($rows as $r):?><tr><td><?=$r['id']?></td><td><?=h($r['complaint_date'])?></td><td><?=h($r['complainer_name'])?></td><td><?=h($r['student_name']??'')?></td><td><?=h($r['status'])?></td><td><a href="?edit=<?=$r['id']?>">Edit</a></td></tr><?php endforeach;?></table></div>
<script>
function mountMS(elId, items, pre=[]){const host=document.getElementById(elId);host.innerHTML='<input type="text" class="ms-in" placeholder="Type student name..."><div class="ms-dd"></div><div class="ms-tags"></div>';const input=host.querySelector('.ms-in'),dd=host.querySelector('.ms-dd'),tags=host.querySelector('.ms-tags');let selected=[...pre];function sync(){tags.innerHTML='';host.querySelectorAll('input[name="student_ids[]"]').forEach(n=>n.remove());selected.forEach(id=>{const it=items.find(x=>x.id==id);if(!it)return;const t=document.createElement('span');t.className='tag';t.textContent=it.label+' ×';t.onclick=()=>{selected=selected.filter(s=>s!=id);sync();};tags.appendChild(t);const h=document.createElement('input');h.type='hidden';h.name='student_ids[]';h.value=id;host.appendChild(h);});}
input.oninput=()=>{const q=input.value.toLowerCase();dd.innerHTML='';items.filter(i=>i.label.toLowerCase().includes(q) && !selected.includes(i.id)).slice(0,8).forEach(i=>{const o=document.createElement('div');o.textContent=i.label;o.className='ms-opt';o.onclick=()=>{selected.push(i.id);input.value='';dd.innerHTML='';sync();};dd.appendChild(o);});};sync();}
mountMS('student-ms', <?=json_encode(array_map(fn($s)=>['id'=>(int)$s['id'],'label'=>$s['code'].' - '.$s['name']],$students))?>, <?=json_encode(($edit && $edit['student_id'])?[(int)$edit['student_id']]:[])?>);
</script>
<?php ui_end(); ?>
