<?php require_once __DIR__ . '/../includes/config.php'; require_once __DIR__ . '/../includes/auth.php'; require_once __DIR__ . '/../includes/layout.php'; require_login();
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(isset($_POST['save_lists'])){ foreach(['routes','attendance_statuses','complaint_types','complaint_statuses'] as $k){ $pdo->prepare('UPDATE settings SET setting_value=? WHERE setting_key=?')->execute([trim($_POST[$k]??''),$k]); }}
 if(isset($_POST['create_user'])) $pdo->prepare('INSERT INTO admins (username,password_hash) VALUES (?,?)')->execute([trim($_POST['new_username']),password_hash($_POST['new_password'],PASSWORD_DEFAULT)]);
 if(isset($_POST['change_password'])) $pdo->prepare('UPDATE admins SET password_hash=? WHERE id=?')->execute([password_hash($_POST['new_user_password'],PASSWORD_DEFAULT),(int)$_POST['admin_id']]);
 if(isset($_POST['upload_logo']) && !empty($_FILES['logo']['tmp_name'])){ @mkdir(__DIR__.'/../uploads',0777,true); $ext=pathinfo($_FILES['logo']['name'],PATHINFO_EXTENSION)?:'png'; $name='logo_'.time().'.'.$ext; move_uploaded_file($_FILES['logo']['tmp_name'],__DIR__.'/../uploads/'.$name); $pdo->prepare("UPDATE settings SET setting_value=? WHERE setting_key='login_logo'")->execute(['/uploads/'.$name]); }
 if(isset($_POST['save_bus'])){ if((int)$_POST['id']>0)$pdo->prepare('UPDATE buses SET name=? WHERE id=?')->execute([trim($_POST['name']),(int)$_POST['id']]); else $pdo->prepare('INSERT INTO buses(name) VALUES(?)')->execute([trim($_POST['name'])]); }
 if(isset($_POST['save_class'])){ if((int)$_POST['id']>0)$pdo->prepare('UPDATE classes SET name=? WHERE id=?')->execute([trim($_POST['name']),(int)$_POST['id']]); else $pdo->prepare('INSERT INTO classes(name) VALUES(?)')->execute([trim($_POST['name'])]); }

 if(isset($_POST['import_students_csv']) && !empty($_FILES['students_csv']['tmp_name'])){
  $h=fopen($_FILES['students_csv']['tmp_name'],'r');
  if($h){
   $first=fgetcsv($h);
   $isHeader=$first && isset($first[0]) && in_array(strtolower(trim((string)$first[0])),['code','student_code','id'],true);
   $rows=[];
   if($first && !$isHeader) $rows[]=$first;
   while(($r=fgetcsv($h))!==false) $rows[]=$r;
   fclose($h);
   foreach($rows as $r){
    if(count($r)<4) continue;
    $code=trim((string)$r[0]); $name=trim((string)$r[1]); $classId=(int)$r[2]; $busId=(trim((string)$r[3])===''?null:(int)$r[3]);
    if($code===''||$name===''||$classId<=0) continue;
    $pdo->prepare('INSERT INTO students (code,name,class_id,bus_id) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name), class_id=VALUES(class_id), bus_id=VALUES(bus_id)')->execute([$code,$name,$classId,$busId]);
   }
  }
 }

 if(isset($_POST['save_student'])){ $id=(int)$_POST['id']; $vals=[trim($_POST['code']),trim($_POST['name']),(int)$_POST['class_id'],(int)($_POST['bus_id']?:0)?:null]; if($id>0){$vals[]=$id; $pdo->prepare('UPDATE students SET code=?,name=?,class_id=?,bus_id=? WHERE id=?')->execute($vals);} else $pdo->prepare('INSERT INTO students(code,name,class_id,bus_id) VALUES(?,?,?,?)')->execute($vals); }
}
$g=[]; foreach(['routes','attendance_statuses','complaint_types','complaint_statuses'] as $k){$g[$k]=(string)$pdo->query("SELECT setting_value FROM settings WHERE setting_key='$k'")->fetchColumn();}
$admins=$pdo->query('SELECT id,username FROM admins ORDER BY username')->fetchAll(); $buses=$pdo->query('SELECT * FROM buses ORDER BY name')->fetchAll(); $classes=$pdo->query('SELECT * FROM classes ORDER BY name')->fetchAll(); $students=$pdo->query('SELECT s.*,c.name class_name,b.name bus_name FROM students s LEFT JOIN classes c ON c.id=s.class_id LEFT JOIN buses b ON b.id=s.bus_id ORDER BY s.name')->fetchAll();
ui_start('Settings');?>
<div class="card"><h2>General Dropdown Settings</h2><form method="post" class="grid"><input type="hidden" name="save_lists" value="1"><input name="routes" value="<?=h($g['routes'])?>" placeholder="routes"><input name="attendance_statuses" value="<?=h($g['attendance_statuses'])?>" placeholder="attendance statuses"><input name="complaint_types" value="<?=h($g['complaint_types'])?>" placeholder="complaint types"><input name="complaint_statuses" value="<?=h($g['complaint_statuses'])?>" placeholder="complaint statuses"><button class="btn">Save</button></form></div>
<div class="card"><h2>Users & Passwords</h2><form method="post" class="grid"><input type="hidden" name="create_user" value="1"><input name="new_username" placeholder="new username" required><input type="password" name="new_password" placeholder="new password" required><button class="btn">Create User</button></form><form method="post" class="grid"><input type="hidden" name="change_password" value="1"><select name="admin_id"><?php foreach($admins as $a):?><option value="<?=$a['id']?>"><?=h($a['username'])?></option><?php endforeach;?></select><input type="password" name="new_user_password" placeholder="new password" required><button class="btn">Change Password</button></form></div>
<div class="card"><h2>Login Logo</h2><form method="post" enctype="multipart/form-data" class="grid"><input type="hidden" name="upload_logo" value="1"><input type="file" name="logo" accept="image/*" required><button class="btn">Upload Logo</button></form></div>
<div class="card"><h2>Buses</h2><form method="post" class="grid"><input type="hidden" name="save_bus" value="1"><input type="hidden" name="id" value="0"><input name="name" placeholder="new bus"><button class="btn">Add Bus</button></form><table><tr><th>ID</th><th>Name</th><th>Edit</th></tr><?php foreach($buses as $b):?><tr><td><?=$b['id']?></td><td><?=h($b['name'])?></td><td><form method="post" class="grid"><input type="hidden" name="save_bus" value="1"><input type="hidden" name="id" value="<?=$b['id']?>"><input name="name" value="<?=h($b['name'])?>"><button class="btn">Save</button></form></td></tr><?php endforeach;?></table></div>
<div class="card"><h2>Classes</h2><form method="post" class="grid"><input type="hidden" name="save_class" value="1"><input type="hidden" name="id" value="0"><input name="name" placeholder="new class"><button class="btn">Add Class</button></form><table><tr><th>ID</th><th>Name</th><th>Edit</th></tr><?php foreach($classes as $c):?><tr><td><?=$c['id']?></td><td><?=h($c['name'])?></td><td><form method="post" class="grid"><input type="hidden" name="save_class" value="1"><input type="hidden" name="id" value="<?=$c['id']?>"><input name="name" value="<?=h($c['name'])?>"><button class="btn">Save</button></form></td></tr><?php endforeach;?></table></div>
<div class="card"><h2>Students</h2>
<form method="post" enctype="multipart/form-data" class="grid"><input type="hidden" name="import_students_csv" value="1"><input type="file" name="students_csv" accept=".csv" required><button class="btn">Import Students CSV</button></form><small>CSV format: code,name,class_id,bus_id (bus_id optional)</small>
<form method="post" class="grid"><input type="hidden" name="save_student" value="1"><input type="hidden" name="id" value="0"><input name="code" placeholder="code"><input name="name" placeholder="name"><select name="class_id"><?php foreach($classes as $c):?><option value="<?=$c['id']?>"><?=h($c['name'])?></option><?php endforeach;?></select><select name="bus_id"><option value="">No bus</option><?php foreach($buses as $b):?><option value="<?=$b['id']?>"><?=h($b['name'])?></option><?php endforeach;?></select><button class="btn">Add Student</button></form><table><tr><th>Code</th><th>Name</th><th>Class</th><th>Bus</th><th>Edit</th></tr><?php foreach($students as $s):?><tr><td><?=h($s['code'])?></td><td><?=h($s['name'])?></td><td><?=h($s['class_name'])?></td><td><?=h($s['bus_name']??'No bus')?></td><td><form method="post" class="grid"><input type="hidden" name="save_student" value="1"><input type="hidden" name="id" value="<?=$s['id']?>"><input name="code" value="<?=h($s['code'])?>"><input name="name" value="<?=h($s['name'])?>"><select name="class_id"><?php foreach($classes as $c):?><option value="<?=$c['id']?>" <?=$s['class_id']==$c['id']?'selected':''?>><?=h($c['name'])?></option><?php endforeach;?></select><select name="bus_id"><option value="">No bus</option><?php foreach($buses as $b):?><option value="<?=$b['id']?>" <?=$s['bus_id']==$b['id']?'selected':''?>><?=h($b['name'])?></option><?php endforeach;?></select><button class="btn">Save</button></form></td></tr><?php endforeach;?></table></div>
<?php ui_end(); ?>